site_name: DbUp Test Docs
theme: readthedocs
repo_url: https://github.com/flatrick/dbup_test
nav:
  - "Home": "index.md"
  - "Tutorials": 
    - "Introduction": "tutorials.md"
    - "SQLite": "tutorial_sqlite.md"
    - "PostgreSQL": "tutorial_postgresql.md"
  - "How-to Guides": 
    - "Introduction": "how-to-guides.md"
  - "Reference":
    - "Introduction": "reference.md"
    - "Settings": "settings.md"  
  - "Explanation": 
    - "Introduction": "explanation.md"
  - "SQL Scripts":
      - "Sources": "script_sources.md"
      - "Settings": "script_settings.md"
