site_name: DbUp Test Docs
theme: readthedocs
repo_url: https://github.com/flatrick/dbup_test
nav:
  - "Home": "index.md"
  - "Tutorials": "tutorials.md"
  - "How-to Guides": "how-to-guides.md"
  - "Reference": "reference.md"
  - "Explanation": "explanation.md"
  - "Settings": "settings.md"  
  - "SQL Scripts":
      - "Sources": "script_sources.md"
      - "Settings": "script_settings.md"
